apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-grpc-server
  namespace: lefebl4
spec:
  selector:
    matchLabels:
      app: ping-grpc-server
  template:
    metadata:
      labels:
        app: ping-grpc-server
      annotations:
        istio-injection: enabled
    spec:
      containers:
      - name: ping-grpc-server
        image: 895940838762.dkr.ecr.us-east-1.amazonaws.com/ping-grpc-server:latest
        imagePullPolicy: Always
        command:
          - "./server"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
