apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ping-grpc-gwy
  namespace: lefebl4
spec:
  selector:
    app: ping-grpc-server
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ping-example
    hosts:
    - ping.infra2.mlife
