apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ping-grpc-gwy
  namespace: lefebl4
spec:
  selector:
    app: istio-ingressgateway
    istio: istio-system
  servers:
  - port:
      number: 443
      name: https-ping
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-system/ping-example
    hosts:
    - "ping.dev2.mlife"
