apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-svc
  namespace: lefebl4
spec:
  hosts:
  - ping.infra2.mlife
  gateways:
  - lefebl4/ping-grpc-gwy
  http:
  - fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 10s
    route:
    - destination:
        host: ping.infra2.mlife
        subset: v1